import { A, DocHeader, Lead, H2, P, Strong, Code, Badge, ParamList, Param, Callout, PrevNext, ToolSignature } from "@/components/docs/ui";
import { CodeBlock } from "@/components/docs/code-block";
import { EyeOff } from "lucide-react";
import { prevNext } from "@/lib/nav";

export const metadata = { title: "emfirge_apply_change · Emfirge Docs", description: "Apply a modeled add, modify, or delete change to an isolated branch." };
export default function Page() { const { prev, next } = prevNext("/docs/tools/apply-change"); return <><DocHeader eyebrow="MCP Tools · Branch" title="emfirge_apply_change" mono><Lead>Apply an add, modify, or delete change to a resource in an isolated branch. This changes the branch model, not AWS.</Lead><div className="mt-5 flex flex-wrap gap-2"><Badge><EyeOff className="size-3.5" /> modeled only</Badge><Badge>no AWS changes</Badge></div></DocHeader>
<ToolSignature name="emfirge_apply_change" args="branch_id, op, resource_type, resource_id, fields?" returns="{ branch_id, num_changes }" /><H2>Parameters</H2><ParamList><Param name="branch_id" type="string" required>Branch ID returned by <A href="/docs/tools/create-branch"><Code>emfirge_create_branch</Code></A>.</Param><Param name="op" type="add | modify | delete" required>Change operation to apply.</Param><Param name="resource_type" type="string" required>Type of infrastructure resource.</Param><Param name="resource_id" type="string" required>ID of the resource to change.</Param><Param name="fields" type="record<string, unknown>">Fields to add or modify; omit for delete or when no fields are needed.</Param></ParamList>
<H2>Example</H2><CodeBlock tabs={[{ label: "arguments", code: `{"branch_id":"branch_456","op":"modify","resource_type":"security_group","resource_id":"NAME_132","fields":{"ingress":[]}}` }]} /><P>Resource IDs from scan responses may be tokens. The MCP automatically expands tokenized scan IDs in <Code>resource_id</Code> and IDs embedded in <Code>fields</Code> before the backend call, then tokenizes the response again.</P>
<H2>Returns</H2><CodeBlock tabs={[{ label: "response", code: `{"branch_id":"branch_456","num_changes":1}` }]} /><P><Code>num_changes</Code> is the number of ordered changes currently recorded on the branch. The operation validates the modeled target and only changes the isolated branch.</P><Callout type="warning" title="Not an apply to AWS"><Strong>Apply</Strong> means apply to the forked model. It does not write infrastructure, call an AWS mutation API, or guarantee application connectivity.</Callout><PrevNext prev={prev} next={next} /></>; }
