export const SOURCE_URL = "https://github.com/theanshsonkar/emfirge";
export const INSTALL = "npx @emfirge/mcp install --privacy=strict";
export const MCP_CONFIG = `{
  "mcpServers": {
    "emfirge": {
      "command": "npx",
      "args": ["-y", "@emfirge/mcp"],
      "env": { "EMFIRGE_PRIVACY": "strict" }
    }
  }
}`;
export const CODEX_CONFIG = `[mcp_servers.emfirge]
command = "npx"
args = ["-y", "@emfirge/mcp"]

[mcp_servers.emfirge.env]
EMFIRGE_PRIVACY = "strict"`;
export const BRANCH_EXAMPLE = `// Tool calls made by your MCP client.
// Replace IDs with values from your own results.
emfirge_create_branch({
  base_analysis_id: "<analysis_id>",
  name: "reduce-db-exposure"
})

emfirge_apply_change({
  branch_id: "<branch_id>",
  op: "modify",
  resource_type: "rds_instance",
  resource_id: "<database_id>",
  fields: { publicly_accessible: false }
})

emfirge_branch_diff({ branch_id: "<branch_id>" })`;
export type DocSection = {
  id: string; title: string; paragraphs?: string[]; code?: string; language?: string;
  note?: string; bullets?: string[]; table?: { headers: string[]; rows: string[][] };
};
export type Doc = { slug: string; title: string; group: string; description: string; sections: DocSection[] };
const section = (id: string, title: string, paragraphs: string[], extra: Partial<DocSection> = {}): DocSection => ({ id, title, paragraphs, ...extra });
export const documents: Doc[] = [
  {
    slug: "quickstart", title: "Developer quickstart", group: "Get started",
    description: "Connect your agent, fork your cloud graph, and inspect a proposed change across its consequences before touching AWS.",
    sections: [
      section("before-you-start", "Before you start", ["You’ll need Node.js 20 or later, an MCP client, and an AWS account you are authorized to inspect. Emfirge’s MCP server runs locally over stdio and calls an Emfirge backend.", "These guides describe the checked-in MCP and engine. Make sure your server exposes the branch tools before following the branch workflow; the hosted deployment and installed package may differ."], {note:"A branch is a model of infrastructure. It does not create a second AWS environment or apply a real change."}),
      section("install", "1. Connect your agent", ["Run the installer in your terminal. It adds Emfirge to detected supported clients, including Claude Code, Claude Desktop, Cursor, Codex, and Kiro. Restart your client after installation.", "For a single client or manual setup, use [Connect agent](/connect)."], { code: INSTALL, language: "Terminal" }),
      section("map", "2. Create your cloud baseline", ["Ask your agent to call `emfirge_setup_help`. Open its CloudFormation link, review the IAM template, and create the read-only role. Once the stack is complete, copy `RoleArn` from Outputs.", "Give the agent the role ARN and the AWS region containing your resources. The region is required: an empty scan in the wrong region is not evidence that your account has no risks."], {code:`emfirge_scan({
  role_arn: "arn:aws:iam::123456789012:role/EmfirgeReadOnly",
  region: "us-east-1"
})`, language:"MCP tool call · example", note:"The account ID above is an example. Use your actual RoleArn and region, then save the analysis_id returned by the scan."}),
      section("branch", "3. Try a change on a branch", ["Create a named branch from the completed analysis, then add a change. Use a database ID that exists in that baseline. Changes accumulate on the branch in order."], {code:BRANCH_EXAMPLE, language:"MCP tool calls"}),
      section("review", "4. Review the consequences", ["Read added and removed relationships, findings, and internet reachability in the diff. Request a verdict to inspect native findings, optional scanner findings, and cost caveats together.", "Review coverage and uncertainty before taking a real action. Your own deployment workflow applies any approved change; Emfirge does not apply it."], {code:'emfirge_branch_verdict({ branch_id: "<branch_id>" })',language:"MCP tool call"}),
    ],
  },
  { slug:"concepts", title:"Key concepts", group:"Get started", description:"One shared model connects your cloud, a proposed change, and the consequences your agent needs to understand.", sections:[
    section("base", "Base snapshot", ["A completed analysis captures the collected infrastructure of an AWS account and region. This is the baseline for a branch. A snapshot reflects collection time; it is not a continuously synchronized view of production."]),
    section("branch", "Branch", ["A branch stores a base snapshot and an ordered list of changes. The engine rebuilds the hypothetical state by replaying those changes. Separate branches let you explore alternatives from the same baseline.", "A branch models resources and relationships. It is not a running environment, a Git checkout, or a production deployment."]),
    section("change", "Change", ["A change adds, modifies, or deletes a supported resource in the model. Its fields must match the resource schema. Changing a resource can affect relationships and findings elsewhere in the collected cloud."]),
    section("lens", "Lens", ["A lens evaluates one aspect of the model. Emfirge’s focused set covers Security and reachability, Configuration checks, Provisioned-cost estimates, Availability and recovery, and What needs a real run; each has its own coverage limits. See [Lenses and coverage](/docs/lenses)."]),
    section("diff", "Diff and verdict", ["The diff explains what changed compared with the base: resources, edges, findings, and reachability. The verdict summarizes selected consequences as `pass`, `warn`, or `block`.", "A pass means the current checks did not trigger a warning or block. It does not prove that a change is safe in a running application."]),
  ]},
  { slug:"branches", title:"Create and compare branches",group:"Work with branches",description:"Explore multiple changes against the same cloud baseline without changing the live account.",sections:[
    section("create", "Create a branch", ["Start with an `analysis_id` returned by a completed scan. Give the branch a name that describes the change you want to explore."], {code:'emfirge_create_branch({\n  base_analysis_id: "<analysis_id>",\n  name: "reduce-db-exposure"\n})',language:"MCP tool call"}),
    section("stack", "Stack changes", ["Each successful `emfirge_apply_change` appends a validated mutation. The engine rebuilds from the same base and applies the entire sequence in order. Only open branches can be changed.", "Use [Apply changes](/docs/changes) for supported resource types and examples."]),
    section("compare", "Compare alternatives", ["Create separate branches from the same base to compare designs. Pass their IDs to the comparison tool. The engine summarizes their modeled changes and outcomes across the documented lenses and ranks them according to its checks."],{code:'emfirge_list_branches({ base_analysis_id: "<analysis_id>" })\n\nemfirge_compare_branches({\n  branch_ids: ["<branch_a>", "<branch_b>"]\n})',language:"MCP tool calls",note:"A better modeled score is not a guarantee of application reliability or lower real-world spend."}),
    section("rollback", "Roll back a change", ["The current backend removes the most recent change. Call rollback again to remove another change; rolling back an empty change list is a no-op. The underlying AWS account is unaffected."],{code:'emfirge_rollback_branch({ branch_id: "<branch_id>" })',language:"MCP tool call"}),
    section("discard", "Discard a branch", ["When an experiment is finished, discard it. The backend marks the branch as discarded, so it can no longer accept mutations. This does not delete cloud resources."],{code:'emfirge_discard_branch({ branch_id: "<branch_id>" })',language:"MCP tool call"}),
  ]},
  { slug:"changes",title:"Apply changes",group:"Work with branches",description:"Describe an infrastructure change as a small, typed mutation of your branch.",sections:[
    section("contract","The change contract",["Every mutation identifies the branch, operation, resource type, and resource ID. `fields` contains the properties to add or modify. Omit it for a delete."],{table:{headers:["Parameter","Type","Meaning"],rows:[["branch_id","string","ID of an open branch"],["op","add | modify | delete","Operation in the model"],["resource_type","string","Supported resource type"],["resource_id","string","Resource identifier"],["fields","object · optional","Schema fields for the mutation"]]}}),
    section("supported","Supported resources",["The current mutation engine supports these five resource types. Collection coverage is broader than mutation coverage; a collected resource is not automatically editable."],{table:{headers:["Resource type","Identity"],rows:[["ec2_instance","Instance ID"],["security_group","Security group ID"],["rds_instance","Database ID"],["s3_bucket","Bucket name"],["lambda_function","Function name"]]}}),
    section("modify","Modify a resource",["For example, disable the public-access flag on an existing database in the model. Use field names from Emfirge’s resource schema, not arbitrary AWS or Terraform property names."],{code:'emfirge_apply_change({\n  branch_id: "<branch_id>",\n  op: "modify",\n  resource_type: "rds_instance",\n  resource_id: "<database_id>",\n  fields: { publicly_accessible: false }\n})',language:"MCP tool call"}),
    section("add-delete","Add or delete a resource",["An add needs the fields required by the resource schema. A delete identifies an existing resource and removes it from the branch model. Review the resulting edges and findings before drawing conclusions.","A removed model relationship does not fully describe application-level dependencies. Dependency breakage beyond the graph needs separate validation."],{code:'emfirge_apply_change({\n  branch_id: "<branch_id>",\n  op: "delete",\n  resource_type: "ec2_instance",\n  resource_id: "<instance_id>"\n})',language:"MCP tool call"}),
  ]},
  {slug:"diffs",title:"Read diffs and verdicts",group:"Work with branches",description:"Understand what changed, why it matters, and what the model cannot establish.",sections:[
    section("diff","Read the infrastructure diff",["Request a diff at any point to compare the rebuilt branch with its original baseline."],{code:'emfirge_branch_diff({ branch_id: "<branch_id>" })',language:"MCP tool call",table:{headers:["Fields","What they describe"],rows:[["added_nodes / removed_nodes / modified_nodes","Resource changes"],["added_edges / removed_edges","Relationship changes"],["added_findings / removed_findings","Changes in native checks"],["newly_internet_reachable / no_longer_internet_reachable","Modeled reachability changes"],["score_before / score_after / score_delta","Score comparison; higher is safer"]]}}),
    section("verdict","Interpret the verdict",["The combined verdict compares native checks with optional Checkov results and includes provisioned-cost notes. It is advisory; the backend does not stop an external AWS apply."],{table:{headers:["Result","Current decision rule"],rows:[["pass","No new findings, new internet reachability, or detected privilege escalation trigger the other states."],["warn","New findings, new reachability, or introduced privilege escalation need review."],["block","A new critical/high finding is on a newly reachable resource or indicates privilege escalation; also used for introduced escalating roles that are internet-reachable."]]}}),
    section("coverage","Read coverage alongside the result",["Check `scanner_available`: false means optional scanner results were not available, not that the scanner found nothing. Read `cost_unknown_notes` even when a numeric cost delta is present.","The current combined-verdict response does not include a universal confidence field. Confidence tiers on graph findings and roadmap commitments should not be treated as fields guaranteed on every tool response."],{note:"A pass is a statement about the checks that ran. Missing scanner coverage, unknown prices, and unmodeled application dependencies still need review."}),
  ]},
  {slug:"lenses",title:"Lenses and coverage",group:"Understand consequences",description:"Evaluate different consequences over the same infrastructure model, with explicit bounds on every conclusion.",sections:[
    section("security","Security and reachability",["The native engine evaluates findings and graph relationships, including internet-reachable resources and privilege-escalation signals. Attack paths and blast radius help explain effects beyond a single changed resource.","These are graph-based predictions. They are not live exploit execution or a complete evaluation of every IAM and network policy."]),
    section("scanners","Configuration checks",["The engine can serialize supported infrastructure and run Checkov as an additional configuration lens. A combined verdict compares before and after findings.","Inspect `scanner_available`. The scanner is optional, and incomplete serialization or an unavailable executable limits coverage."]),
    section("cost","Provisioned-cost estimates",["The current engine uses a small curated pricing table with a stated region and monthly-hour assumption. It reports known provisioned charges and identifies unknown prices or usage-based costs.","A live AWS Price List integration is a roadmap direction. Current values are estimates, not your AWS bill. RDS or other unsupported prices must not be invented."],{table:{headers:["Cost basis","Interpretation"],rows:[["provisioned-estimate","A supported resource with a known table price"],["usage-based-unknown","Requires actual usage information"],["price-unavailable","No supported price for the resource"]]}}),
    section("resilience","Availability and recovery",["Native rules and category scores include infrastructure configuration signals for availability and disaster recovery. These do not predict uptime, failover timing, or whether an application can serve a particular load."]),
    section("runtime","What needs a real run",["Application latency, throughput, runtime correctness, recovery time, and usage-based spend require execution or measured telemetry. Emfirge’s model does not produce those measurements."]),
  ]},
  {slug:"safety",title:"Safety and model limits",group:"Understand consequences",description:"Keep cloud access read-only and use branches to inspect modeled consequences through the documented lenses.",sections:[
    section("read-only","Read-only AWS access",["Emfirge collects infrastructure through an IAM role assumed with AWS STS. Review the CloudFormation template and its trust policy before connecting your account. The analysis and mutation tools do not apply changes to real AWS resources.","The setup flow creates an IAM role in your account. You approve that setup in AWS; subsequent proposed infrastructure changes stay in Emfirge’s model."]),
    section("advisory","Advisory by design",["A `block` verdict is an analysis result. Emfirge does not physically prevent an agent, user, or pipeline with separate AWS credentials from deploying. Any approval policy must be enforced by your own workflow."]),
    section("privacy","Privacy and data flow",["The local MCP server sends requests to the configured Emfirge backend. The backend collects and processes infrastructure information. Strict privacy mode tokenizes supported identifiers in covered tool responses before they reach the host model; it does not mean infrastructure stays only on your computer.","The checked-in branch handlers return backend JSON directly and do not apply the same tokenization wrapper used by scan and findings tools. Do not assume strict mode redacts every branch response."],{note:"Treat local token mappings and analysis output as sensitive infrastructure data. Review the client and backend behavior for the tools you use."}),
    section("confidence","Coverage and uncertainty",["Graph confidence and coverage depend on collected fields, modeled relationships, and the checks that ran. A model cannot establish application behavior or complete runtime reachability.","Prefer a precise limitation over an unsupported promise. Review scanner availability and unknown cost notes before taking action."]),
    section("revoke","Revoke AWS access",["Remove the CloudFormation stack that created the read-only role to revoke that role’s access. Removing the MCP client configuration alone does not remove the IAM role or stored scan data."]),
  ]},
  {slug:"configuration",title:"Configuration",group:"Integrate",description:"Configure the MCP transport, backend destination, and privacy settings for your agent.",sections:[
    section("stdio","MCP over stdio",["Emfirge is a local process launched by your MCP client. It communicates with the client over stdio and sends HTTP requests to the configured backend. Use the following server entry in a client that accepts JSON MCP configuration."],{code:MCP_CONFIG,language:"JSON"}),
    section("codex","Codex configuration",["The Emfirge installer writes this TOML block for Codex. Merge it with your existing configuration rather than replacing the whole file."],{code:CODEX_CONFIG,language:"~/.codex/config.toml"}),
    section("environment","Environment variables",[],{table:{headers:["Variable","Purpose"],rows:[["EMFIRGE_BASE_URL","Backend API URL; defaults to https://emfirge.cloud/api"],["EMFIRGE_PRIVACY","strict (default), balanced, or off"],["EMFIRGE_TRUSTED_ACCOUNT_ID","Trusted AWS account used by setup help"],["EMFIRGE_EXTERNAL_ID","STS ExternalId; default aws-risk-agent"],["EMFIRGE_TEMPLATE_URL","CloudFormation template URL used by setup help"]]}}),
    section("self-host","Use your own backend",["Set `EMFIRGE_BASE_URL` in the MCP server environment to your backend’s API URL. Configure the role trust and ExternalId for that backend. A custom URL does not install or start an engine for you.","Keep the MCP tool set and backend routes compatible. If branch tools are absent, use a matching build of the client and engine."],{code:'"env": {\n  "EMFIRGE_BASE_URL": "https://your-emfirge-host.example/api",\n  "EMFIRGE_PRIVACY": "strict"\n}',language:"JSON server environment"}),
    section("verify","Inspect local setup",["The status command reports configured clients and privacy settings. Confirm that your agent can list Emfirge tools to verify the connection."],{code:"npx @emfirge/mcp status",language:"Terminal"}),
  ]},
  {slug:"troubleshooting",title:"Troubleshooting",group:"Resources",description:"Resolve common setup, scanning, and branch issues with a focused check.",sections:[
    section("tools","Emfirge tools do not appear",["Confirm Node.js 20 or later is available to your desktop client. Run `npx @emfirge/mcp status`, check the client’s MCP configuration, and restart the client.","If scan tools appear but branch tools do not, the installed MCP version may not match this source. Use matching MCP and engine builds."]),
    section("access","Access denied or 403",["Review the IAM role ARN, trusted account, and ExternalId. Ask your agent to call `emfirge_setup_help` to inspect the setup flow. Confirm that the role’s permissions allow the collection calls required by your backend."]),
    section("empty","The scan is empty",["Confirm the region with the account owner. Emfirge requires an explicit region because most resources are regional. Also check collection permissions. An empty result does not establish that the entire AWS account has no risks."]),
    section("not-found","Analysis or branch not found",["Use the exact ID returned by the tool and the same backend that created it. For an analysis, run a new scan if its stored record is no longer available. For branch-route errors, check client/backend version compatibility."]),
    section("mutation","A change is rejected",["Check that the branch is open, the resource type is supported, and the target resource exists for modify/delete. Unknown fields are rejected. See [Apply changes](/docs/changes) for the contract."]),
    section("limits","Timeouts and limits",["The scan client uses a streaming backend endpoint and waits up to 240 seconds. Check backend health and account size after a timeout. For a 429 response, follow the limit and reset information returned by your backend."]),
    section("scanner","Scanner unavailable",["A verdict may still return native results when Checkov is unavailable. Inspect `scanner_available`; verify the engine’s scanner installation and serialization support before treating scanner coverage as complete."]),
  ]},
  {slug:"glossary",title:"Glossary",group:"Resources",description:"A shared vocabulary for modeling cloud changes with Emfirge.",sections:[
    section("terms","Terms",[],{table:{headers:["Term","Meaning"],rows:[["Analysis","The result of collecting and evaluating an AWS account and region."],["Base","The saved infrastructure snapshot a branch starts from."],["Branch","A base snapshot plus an ordered list of hypothetical changes."],["Mutation","One add, modify, or delete operation in the model."],["Graph","Resources represented as nodes, connected by typed relationships."],["Lens","An evaluation of a particular aspect of the infrastructure model."],["Diff","The resources, relationships, findings, and reachability that changed."],["Verdict","An advisory pass, warn, or block from the current evaluation."],["Attack path","A modeled route from an entry point toward another resource."],["Blast radius","The modeled resources reachable after a compromise or change."],["MCP","Model Context Protocol: the interface used by an agent to call Emfirge tools."],["Needs a real run","A question the model cannot resolve without execution or measured data."]]}}),
  ]},
];

export type Tool = { name: string; description: string; params: string; group: string };
export const mcpTools: Tool[] = [
  {name:"emfirge_setup_help",description:"Return the CloudFormation setup link and read-only role instructions.",params:"No parameters.",group:"Setup and baseline"},
  {name:"emfirge_scan",description:"Collect an AWS account and region and return an analysis_id.",params:"role_arn: IAM role ARN · required; region: AWS region · required",group:"Setup and baseline"},
  {name:"emfirge_create_branch",description:"Create an isolated branch from a completed analysis.",params:"base_analysis_id: string · required; name: non-empty string · required",group:"Branch workflow"},
  {name:"emfirge_apply_change",description:"Append an add, modify, or delete mutation to the branch model.",params:"branch_id, resource_type, resource_id: string · required; op: add | modify | delete · required; fields: object · optional",group:"Branch workflow"},
  {name:"emfirge_branch_diff",description:"Compare a branch against its base: resources, relationships, findings, and reachability.",params:"branch_id: string · required",group:"Branch workflow"},
  {name:"emfirge_branch_verdict",description:"Evaluate the branch with native findings, optional scanner results, and cost notes.",params:"branch_id: string · required",group:"Branch workflow"},
  {name:"emfirge_rollback_branch",description:"Remove the most recent change from a branch in the current backend.",params:"branch_id: string · required",group:"Branch workflow"},
  {name:"emfirge_discard_branch",description:"Mark a branch as discarded without changing AWS.",params:"branch_id: string · required",group:"Branch workflow"},
  {name:"emfirge_list_branches",description:"List branches, optionally filtered by their base analysis.",params:"base_analysis_id: string · optional",group:"Branch workflow"},
  {name:"emfirge_compare_branches",description:"Compare modeled changes and outcomes for one or more branches.",params:"branch_ids: non-empty string array · required",group:"Branch workflow"},
  {name:"emfirge_get_findings",description:"Retrieve findings from a scan, optionally filtered by severity.",params:"analysis_id: string · required; severity: Critical | Moderate | Low · optional",group:"Analysis tools"},
  {name:"emfirge_attack_paths",description:"Read modeled internet-to-internal paths, critical resources, orphans, and graph statistics.",params:"analysis_id: string · required",group:"Analysis tools"},
  {name:"emfirge_verify_fix",description:"Simulate one supported rule remediation against an analysis. Not every rule has a fix mutation.",params:"analysis_id, rule_id, resource_id: string · required",group:"Analysis tools"},
  {name:"emfirge_simulate_breach",description:"Evaluate a graph-based scenario without executing a real exploit.",params:"analysis_id: string · required; query: string, 3–500 characters · required",group:"Analysis tools"},
  {name:"emfirge_check_compliance",description:"Retrieve mapped CIS AWS Foundations 1.5 or SOC 2 control results. These checks do not constitute certification.",params:"analysis_id: string · required; framework: cis-aws-1.5 | soc2 · optional",group:"Analysis tools"},
];
const mcpIndexRoutes: Record<string, string> = {
  emfirge_setup_help: "/docs/tool-setup-help",
  emfirge_scan: "/docs/tool-scan",
  emfirge_get_findings: "/docs/tool-get-findings",
  emfirge_attack_paths: "/docs/tool-attack-paths",
  emfirge_create_branch: "/docs/tool-create-branch",
  emfirge_apply_change: "/docs/tool-apply-change",
  emfirge_branch_diff: "/docs/tool-branch-diff",
  emfirge_branch_verdict: "/docs/tool-branch-verdict",
  emfirge_list_branches: "/docs/tool-list-branches",
  emfirge_rollback_branch: "/docs/tool-rollback-branch",
  emfirge_verify_fix: "/docs/tool-verify-fix",
  emfirge_compare_branches: "/docs/tool-compare-branches",
  emfirge_check_compliance: "/docs/tool-check-compliance",
  emfirge_discard_branch: "/docs/tool-discard-branch",
  emfirge_simulate_breach: "/docs/tool-simulate-breach",
};
const mcpIndexGroups: [string, string[]][] = [
  ["Setup", ["emfirge_setup_help", "emfirge_scan"]],
  ["Scan and inspect", ["emfirge_get_findings", "emfirge_attack_paths", "emfirge_simulate_breach"]],
  ["Branch lifecycle", ["emfirge_create_branch", "emfirge_apply_change", "emfirge_branch_diff", "emfirge_list_branches", "emfirge_rollback_branch", "emfirge_discard_branch"]],
  ["Analysis and verdict", ["emfirge_branch_verdict", "emfirge_verify_fix", "emfirge_compare_branches"]],
  ["Compliance", ["emfirge_check_compliance"]],
];
documents.splice(7, 0, {slug:"mcp",title:"MCP tool reference",group:"Integrate",description:"The typed interface your agent uses to fork infrastructure, explore changes, and inspect their consequences across the documented lenses.",sections:[
  section("using-tools", "Using the tools", ["Emfirge runs as an MCP server that your agent invokes over the local stdio connection. Each tool below is a registered operation; select its linked page for the full parameter and response details.", "Persist the analysis_id and branch_id returned by your own calls. Do not substitute IDs from screenshots or examples. A compatible engine is required for branch operations."]),
  ...mcpIndexGroups.map(([id, names]) => section(id, id, [], {table: {headers: ["Tool", "What it does"], rows: names.map(name => { const tool = mcpTools.find(candidate => candidate.name === name)!; return [`[${tool.name}](${mcpIndexRoutes[name]})`, tool.description]; })}})),
]});
const extra = (slug: string, title: string, group: string, description: string, sections: DocSection[]): Doc => ({slug,title,group,description,sections});
const legacyDocs: Doc[] = [
  extra("how-it-works","How the fork works","Get started","Build a read-only graph, fork it, model a change, and inspect consequences before deployment.",[section("harness","The harness between AI and cloud", ["An agent should not need direct access to a live account. Emfirge sits between the agent and cloud as a safe workspace: the agent proposes, Emfirge branches and measures the change, and your own pipeline decides what to apply." ]),section("workflow","The workflow", ["A scan builds a connected graph from a read-only role. Fork a completed analysis with `emfirge_create_branch`, add an operation with `emfirge_apply_change`, then inspect `emfirge_branch_diff` and `emfirge_branch_verdict`."],{code:'emfirge_create_branch({ base_analysis_id: "<analysis_id>", name: "restrict-public-access" })\nemfirge_apply_change({ branch_id: "<branch_id>", op: "modify", resource_type: "rds_instance", resource_id: "<database_id>", fields: { publicly_accessible: false } })\nemfirge_branch_verdict({ branch_id: "<branch_id>" })',language:"MCP tool calls"}),section("limits","Honest limits",["Branches are models, not deployments. Emfirge does not apply branch changes to AWS, and a result from any one lens does not prove application connectivity or every operational consequence. Re-scan when the live environment changes."])]),
  extra("graph","The infrastructure graph","Understand consequences","Explore attack paths, blast radius, chokepoints, and toxic combinations as queries over one graph.",[section("map","What the graph is",["Every scanned resource becomes a node and every relationship a directed edge. The public internet is a first-class node, so reachability is a literal path. The engine models roughly 20 service types and relationships such as `REACHES`, `uses_iam_role`, `can_access`, `REFERENCES_SECRET`, and subnet/VPC containment." ]),section("weights","Rank routes by effort",["Edges carry exploit-difficulty weights from 0 to 3. Path ranking uses effort, not simply hop count: a five-hop route of trivial steps can outrank a two-hop route needing a shell and stolen credentials."],{table:{headers:["Weight","Meaning"],rows:[["0","No additional modeled difficulty"],["1","Low modeled effort"],["2","Moderate modeled effort"],["3","High modeled effort"]]}}),section("queries","One graph, many queries",["Attack paths are ranked by effort. Blast radius is an outbound-only search from a node. Chokepoints use betweenness centrality. Toxic combinations are nine curated multi-signal patterns, and orphaned resources are disconnected nodes often indicating cleanup or cost work."]),section("limits","Rules and limits",["The engine runs 58 deterministic rules across 17 service families and produces a 0–100 posture score, higher is safer, across security, availability, cost, and disaster recovery. Path-finding and blast radius are capped at 5 hops. The graph is a scan snapshot, not live AWS; coverage and exploit weights are bounded heuristics."])]),
  extra("security","Security as one lens","Safety & privacy","Emfirge is the harness between your AI agent and cloud: fork the infrastructure graph, model a proposed change, and inspect its consequences across the documented lenses before production. Security and reachability are one lens; read-only IAM access, scoped trust, temporary credentials, deterministic analysis, and revocation keep that lens bounded.",[section("role","The role",["Emfirge reads through a read-only IAM role you own and control, with no write permissions. The role trusts the configured account with ExternalId `aws-risk-agent` and uses one-hour temporary STS credentials that are never stored. Delete the CloudFormation stack to revoke access."]),section("setup","Set it up",["Ask your assistant for setup help, open the pre-filled CloudFormation URL, acknowledge the IAM-resources checkbox, create the stack (about 30 seconds), and copy `RoleArn` from Outputs before scanning."]),section("deterministic","Deterministic backend",["Scanning, rules, graph analysis, and verify-fix are pure computation: the same input produces the same output. Prose summaries are the only place a model is used, never inside the MCP path."]),section("errors","Retention and errors",["Scan data is retained for 90 days and then auto-deleted; the CLI can wipe it immediately. A 403 usually means trust or ExternalId, a 404 means the analysis was not found, and a 429 means the five-scans-per-account-per-day limit."])]),
  extra("privacy","Privacy modes","Safety & privacy","Control which recognized AWS identifiers are tokenized before results reach your model.",[section("tokenization","How tokenization works",["The local MCP replaces recognized AWS identifiers with stable local tokens such as `SG_001` and `S3_001`. Later calls expand tokens locally, call the backend, and tokenize again. The mapping stays on your machine and is not sent to Emfirge or the model."],{code:'LLM sees:       "SG_001 reaches S3_001"\nlocal mapping:  SG_001 = <local security-group ID>\n                S3_001 = <local bucket ID>',language:"Example"}),section("modes","The three modes",["`strict` (default) tokenizes recognized AWS IDs, ARNs, account IDs, names, and IPs. `balanced` tokenizes common identifiers while retaining selected context. `off` leaves identifiers raw."]),section("change","Change the mode",["Use the CLI or set `EMFIRGE_PRIVACY` in client configuration."],{code:"npx @emfirge/mcp privacy\nnpx @emfirge/mcp privacy strict",language:"Terminal"}),section("boundary","Backend and report URLs",["The backend receives data required for analysis. Credentials in presigned report URLs are scrubbed. Derived graph labels may not be recognized identifiers, so tokenization is not a completeness guarantee."])]),
  extra("cli","CLI reference","CLI","Install, inspect, configure, and remove the Emfirge MCP client from the terminal.",[section("overview","The package and server",["With no subcommand the package runs as an MCP stdio server; with a subcommand it manages your install."]),section("commands","Commands",["`install` wires the server into detected client configs; `--privacy` avoids the prompt and defaults to strict. `status` prints wired clients, backend URL, and privacy mode. `privacy` shows or sets strict, balanced, or off. `tokens` lists local mappings at `~/.emfirge/tokens.json`, which never leaves your machine."],{code:"npx @emfirge/mcp --help\nnpx @emfirge/mcp install --privacy=strict\nnpx @emfirge/mcp status\nnpx @emfirge/mcp privacy strict\nnpx @emfirge/mcp tokens",language:"Terminal"}),section("purge","Purge scan data",["`purge --role-arn <role-arn>` deletes local token mappings and server-side scan data for that role. This permanently deletes records and has no undo."],{code:"npx @emfirge/mcp purge --role-arn arn:aws:iam::<account>:role/<name>",language:"Terminal",note:"Irreversible"})]),
  extra("self-host","Self-hosting","Self-hosting","Point the thin MCP client at your own backend with environment variables.",[section("backend","Point at your own backend",["The default backend is `https://emfirge.cloud/api`. Set `EMFIRGE_BASE_URL` in each client config. The thin MCP calls backend endpoints and tokenizes responses locally; dashboard URLs derive from the API base by stripping `/api`." ]),section("environment","Environment variables",[],{table:{headers:["Variable","Purpose and default"],rows:[["EMFIRGE_BASE_URL","Backend URL; default https://emfirge.cloud/api"],["EMFIRGE_PRIVACY","strict, balanced, or off"],["EMFIRGE_TRUSTED_ACCOUNT_ID","Trusted AWS account; default 000000000000"],["EMFIRGE_EXTERNAL_ID","Trust ExternalId; default aws-risk-agent"],["EMFIRGE_TEMPLATE_URL","Template URL used by setup help"]]}}),section("license","Open source",["The MCP and a public backend mirror are open source under BUSL 1.1 (free for non-production and small production use; converts to Apache 2.0 in 2030)."])]),
  extra("faq","FAQ","Reference","Plain-language answers about Emfirge, AWS access, privacy, limits, and self-hosting.",[section("basics","What does Emfirge do?",["Emfirge is the harness between your AI agent and cloud: it forks the infrastructure graph so you can model a proposed change and inspect its consequences before applying anything. Security and reachability are one lens; ask what to fix first, how someone could reach a database, or whether a change helps."]),section("start","What do I need?",["An AWS account, a region, and a read-only connection. Start with the [quickstart](/docs/quickstart). MCP is simply the connection that lets an AI assistant use tools. A demo uses made-up infrastructure with the real analysis engine."]),section("safety","Will it change anything?",["No. Possible fixes run on a temporary copy of the cloud map. Revoke access by deleting the setup stack. See [Security model](/docs/security) and [Privacy modes](/docs/privacy)."]),section("limits","How long and how often?",["Scans usually take 30–60 seconds and are limited to five per AWS account per day. Findings, attack paths, possible fixes, and compliance checks do not consume another scan. Coverage is not every AWS issue."]),section("next","What after a finding?",["Inspect the top-ranked item, affected routes, and suggested fix. Emfirge provides evidence; your team reviews and applies the final fix. Self-hosting is available in the [self-hosting](/docs/self-host) guide."])]),
];
const toolInfo: Record<string,[string,string,string,string,string[],string]> = {
  "tool-scan":["emfirge_scan","Build the read-only cloud graph that your agent can fork and evaluate across modeled consequences.","role_arn: string · required; region: string · required",`{
  "role_arn": "arn:aws:iam::123456789012:role/EmfirgeReadOnly",
  "region": "us-east-1"
}`, ["Returns an overall_risk_score (0–100, higher is safer), matching overall_risk_level, per-category security_score, availability_score, disaster_recovery_score, and cost_score, plus analysis_id, region_analyzed, simulation_baseline, grouped critical_risks, moderate_risks, and low_risks arrays, toxic_combinations, and total_resources_scanned.","Resource IDs are tokenized to NAME_### by default. The score is deterministic and read-only; there is no separate counts object because tallies live under simulation_baseline. Hold on to analysis_id for get_findings, attack_paths, verify_fix, simulate_breach, and check_compliance.","The result ends with a line such as Scans remaining today: 4/5. A real scan takes 30–60 seconds and streams to stay under proxy timeouts. The limit is five scans per AWS account per day, resetting at midnight UTC; 429 means the limit was reached. Other tools use a completed scan and do not consume this budget."],`{
  "analysis_id": "7f3c9a2e-4b1d-4c8a-9f2e-1a2b3c4d5e6f",
  "region_analyzed": "us-east-1",
  "overall_risk_score": 3,
  "overall_risk_level": "CRITICAL",
  "security_score": 18,
  "availability_score": 96,
  "disaster_recovery_score": 90,
  "cost_score": 97,
  "simulation_baseline": { "critical_count": 15, "moderate_count": 17 },
  "critical_risks": [ /* … full finding objects … */ ],
  "moderate_risks": [ /* … */ ],
  "low_risks": [ /* … */ ],
  "toxic_combinations": [ /* … */ ],
  "total_resources_scanned": 51
}`],
  "tool-get-findings":["emfirge_get_findings","Get the full findings list for a previous scan, optionally filtered by severity.","analysis_id: string · required; severity: Critical | Moderate | Low · optional",`{
  "analysis_id": "7f3c9a2e-4b1d-4c8a-9f2e-1a2b3c4d5e6f",
  "severity": "Critical"
}`, ["Each finding carries rule_id, category, severity, confidence, issue, recommendation, aws_service, resource_id, resource_type, region, attack_path, blast_radius, mitre_technique_id, and mitre_technique_name.","attack_path is an array of node IDs, not a string; blast_radius is an integer count of reachable resources. Some attack_path hops may be un-tokenized graph labels such as iam-role-AppServerRole.","Findings are grouped by severity into critical_risks, moderate_risks, and low_risks. A scan also returns best_practices, cost_findings, and toxic_combinations. This is read-only and does not consume scan budget; if analysis_id is not found, run a scan first."],`{
  "critical_risks": [{
    "rule_id": "EMFIRGE-EC2-002", "category": "Security", "severity": "Critical", "confidence": "HIGH",
    "issue": "SSH port 22 is open to the entire internet (0.0.0.0/0)",
    "recommendation": "Restrict SSH access to your specific IP address only", "aws_service": "EC2",
    "resource_id": "NAME_132", "resource_type": "security_group", "region": "us-east-1",
    "attack_path": ["NAME_132", "NAME_140", "iam-role-AppServerRole", "acme-prod-customers"],
    "blast_radius": 15, "mitre_technique_id": "T1021.004", "mitre_technique_name": "Remote Services: SSH"
  }]
}`],
  "tool-attack-paths":["emfirge_attack_paths","Query the modeled graph for internet-to-internal paths, chokepoints, and orphaned resources as one view of cloud consequences.","analysis_id: string · required",`{ "analysis_id": "7f3c9a2e-4b1d-4c8a-9f2e-1a2b3c4d5e6f" }`, ["Each path contains finding_id, finding_title, severity, and path, an ordered array of node IDs. Paths are ranked by exploit difficulty.","critical_resources identify crown jewels with node_id, label, type, finding_count, max_severity, blast_radius, centrality, and exploit_distance. High-centrality entries are chokepoints where hardening one resource severs the most paths.","orphaned_resources and stats round out the graph. stats contains total_nodes, total_edges, orphaned_count, estimated_monthly_waste, node_types, and edge_types. Some node IDs are raw graph labels rather than NAME_### tokens. Feed a chokepoint into verify_fix to test whether hardening collapses paths."],`{
  "paths": [{ "finding_id": "EMFIRGE-EC2-002", "finding_title": "SSH port 22 is open to the entire internet (0.0.0.0/0)", "severity": "critical", "path": ["NAME_132", "NAME_140", "iam-role-AppServerRole", "acme-prod-customers"] }],
  "critical_resources": [{ "node_id": "acme-prod-customers", "label": "RDS: acme-prod-customers", "type": "rds_instance", "finding_count": 6, "max_severity": "Critical", "blast_radius": 22, "centrality": 0.15415, "exploit_distance": 6 }],
  "orphaned_resources": [{ "id": "NAME_154", "type": "ebs_volume", "label": "EBS: 50GB", "estimated_monthly_cost": 5, "reason": "Unattached EBS volume (available state)" }],
  "stats": { "total_nodes": 53, "total_edges": 88, "orphaned_count": 6, "estimated_monthly_waste": 43.65, "node_types": {}, "edge_types": {} }
}`],
  "tool-create-branch":["emfirge_create_branch","Create an isolated infrastructure branch from a completed analysis to model changes safely before applying anything to AWS.","base_analysis_id: string · required; name: string · required",`{ "base_analysis_id": "analysis_123", "name": "restrict-public-access" }`, ["Returns branch_id, which identifies the isolated model for apply_change, diff, verdict, rollback, discard, and comparison calls. The base snapshot remains immutable.","The branch is modeled only: creating it forks saved scan data, does not assume write permissions, and does not mutate AWS."],`{ "branch_id": "branch_456" }`],
  "tool-setup-help":["emfirge_setup_help","Return a ready-to-click CloudFormation deploy URL and instructions for creating the read-only IAM role.","No parameters.","Help me set up Emfirge", ["The response contains a CloudFormation quick-create URL pre-filled with ExternalId aws-risk-agent and step-by-step instructions: open it, acknowledge IAM resources, create the stack (about 30 seconds), then copy RoleArn from Outputs and provide it with a region to emfirge_scan.","The RoleArn starts with arn:aws:iam::. The default trusted account is 000000000000 and ExternalId is aws-risk-agent; self-hosting can override them with EMFIRGE_TRUSTED_ACCOUNT_ID and EMFIRGE_EXTERNAL_ID.","Terminal clients including Claude Code, Codex CLI, and Kiro CLI hide tool output by default. If only ‘click the link above’ appears, ask the assistant to print the deploy URL verbatim. A 403 is a reason to call setup_help again."],`Deploy URL: https://console.aws.amazon.com/cloudformation/home#/stacks/quickcreate?templateURL=…&stackName=EmfirgeReadOnlyStack&param_ExternalId=aws-risk-agent

1. Open the URL.
2. Tick the IAM acknowledgement and Create stack (~30s).
3. On CREATE_COMPLETE, copy RoleArn from Outputs.
4. Paste the RoleArn back here and run a scan.`],
  "tool-branch-verdict":["emfirge_branch_verdict","Evaluate an isolated infrastructure branch across the documented consequence lenses, including security findings and proposed changes.","branch_id: string · required",`{ "branch_id": "branch_456" }`, ["verdict is block, warn, or pass. The response reports native_added, native_removed, scanner_added, scanner_removed, score_before, score_after, score_delta, newly_internet_reachable, no_longer_internet_reachable, cost_delta_monthly_usd, cost_unknown_notes, introduces_privilege_escalation, limits_introduced, limits_resolved, and summary.","scanner_status gives each borrowed scanner’s outcome, scanner_available says whether any scanner ran, and coverage_warnings explains missing or disabled lenses. Non-empty warnings mean degraded coverage and the result must not be presented as complete coverage or a safety guarantee.","block flags a modeled blocking risk; warn flags a modeled concern; pass means no modeled blocking or warning condition was found by the available analysis. None guarantees safe deployment or application behavior."],`{
  "verdict": "warn", "native_added": [], "native_removed": [], "scanner_added": [], "scanner_removed": [],
  "score_before": 72, "score_after": 70, "score_delta": -2, "newly_internet_reachable": [], "no_longer_internet_reachable": [],
  "scanner_available": false, "scanner_status": { "checkov": "disabled", "trivy": "disabled", "cloudsplaining": "disabled" },
  "coverage_warnings": ["borrowed scanners are disabled on this verdict (native rules only) — this verdict is NOT full coverage"],
  "cost_delta_monthly_usd": 12.5, "cost_unknown_notes": [], "introduces_privilege_escalation": false,
  "limits_introduced": [], "limits_resolved": [], "summary": "verdict=warn; ..."
}`],
  "tool-branch-diff":["emfirge_branch_diff","Show the infrastructure diff for an isolated branch compared with its base analysis.","branch_id: string · required",`{ "branch_id": "branch_456" }`, ["The response contains added_nodes, removed_nodes, modified_nodes, added_edges, removed_edges, added_findings, removed_findings, score_before, score_after, score_delta, newly_internet_reachable, and no_longer_internet_reachable.","Arrays describe modeled node, edge, and finding changes against the immutable base. Scores are 0–100 posture scores where higher is safer; score_delta is evidence about the model, not a deployment guarantee.","Branch changes remain isolated and do not mutate AWS. Re-scan when the live account has changed since the base analysis."],`{
  "added_nodes": ["NAME_201"], "removed_nodes": [], "modified_nodes": ["NAME_132"], "added_edges": [], "removed_edges": [],
  "added_findings": [], "removed_findings": [{ "rule_id": "..." }], "score_before": 72, "score_after": 78, "score_delta": 6,
  "newly_internet_reachable": [], "no_longer_internet_reachable": ["NAME_201"]
}`],
  "tool-list-branches":["emfirge_list_branches","List isolated infrastructure branches, optionally filtered by their base analysis.","base_analysis_id: string · optional",`{ "base_analysis_id": "analysis_123" }`, ["Omit base_analysis_id to list all branches. Each item reports branch_id, name, status, base_analysis_id, and num_changes, the number of ordered modeled changes.","Listing is read-only and does not affect AWS."],`[{ "branch_id": "branch_456", "name": "restrict-public-access", "status": "open", "base_analysis_id": "analysis_123", "num_changes": 1 }]`],
  "tool-rollback-branch":["emfirge_rollback_branch","Remove the most recent modeled change from an isolated branch without changing AWS.","branch_id: string · required",`{ "branch_id": "branch_456" }`, ["Each call removes the most recent modeled change. Repeated calls can return the branch to its base state; with no changes rollback is a safe no-op.","The branch remains open, its base analysis is unchanged, and rollback only changes isolated branch history; it never reverts or writes anything in AWS."],`{ "branch_id": "branch_456", "name": "restrict-public-access", "status": "open", "base_analysis_id": "analysis_123", "num_changes": 0 }`],
  "tool-verify-fix":["emfirge_verify_fix","Simulate fixing a finding on a clone of the graph without applying any change.","analysis_id: string · required; rule_id: string · required; resource_id: string · required",`{
  "rule_id": "EC2-002",
  "resource_id": "NAME_132",
  "analysis_id": "7f3c9a2e-4b1d-4c8a-9f2e-1a2b3c4d5e6f"
}`, ["The clone applies the rule mutation, rebuilds, re-runs every rule, and returns score delta plus findings that resolve. findings_removed and findings_added are arrays of full finding objects, not counts; score_before and score_after are 0–100 posture scores where higher is safer.","safe_to_apply is advisory: true means the cloned branch showed no new modeled security finding and no score worsening. Say ‘no modeled security regression’ or ‘no new exposure detected’; this does not establish live safety, deployment, or application connectivity.","rule_id accepts full or short form such as EMFIRGE-EC2-002 or EC2-002. resource_id accepts a raw ID or NAME_### token, which is expanded locally. Deterministic simulation covers EC2-002, EC2-003, EC2-009, S3-001, S3-002, S3-003, RDS-002, RDS-003, RDS-004, RDS-006, WAF-001, GUARD-001, and CW-001. Other findings return guidance; MCP does not open pull requests. The real scan and AWS are not mutated."],`{
  "can_simulate": true,
  "findings_removed": [{ "rule_id": "EMFIRGE-EC2-002", "severity": "Critical" /* … full finding object … */ }],
  "findings_added": [], "toxic_combos_resolved": ["SSH_OPEN_NO_GUARDDUTY"], "toxic_combos_created": [],
  "score_before": 3, "score_after": 3, "score_delta": 0, "safe_to_apply": true
}`],
  "tool-apply-change":["emfirge_apply_change","Apply an add, modify, or delete change to a resource in an isolated branch; this changes the branch model, not AWS.","branch_id: string · required; op: add | modify | delete · required; resource_type: string · required; resource_id: string · required; fields: record<string, unknown> · optional",`{ "branch_id": "branch_456", "op": "modify", "resource_type": "security_group", "resource_id": "NAME_132", "fields": { "ingress": [] } }`, ["fields contains fields to add or modify; omit it for delete or when no fields are needed. The operation validates the modeled target and returns the number of ordered changes currently recorded.","Resource IDs from scan responses may be tokens. The MCP expands tokenized IDs in resource_id and IDs embedded in fields before the backend call, then tokenizes the response again.","Apply means apply to the forked model. It does not write infrastructure, call an AWS mutation API, or guarantee application connectivity."],`{ "branch_id": "branch_456", "num_changes": 1 }`],
  "tool-compare-branches":["emfirge_compare_branches","Compare one or more isolated infrastructure branches and their modeled consequences across the documented lenses, including security outcomes.","branch_ids: string[] · required",`{ "branch_ids": ["branch_456", "branch_789"] }`, ["Each branch summary reports score_after, score_delta, added_nodes, removed_nodes, newly_internet_reachable, no_longer_internet_reachable, added_findings, removed_findings, and has_privilege_escalation.","ranking orders branches safest-first using deterministic comparison; it is not a deployment recommendation or safety guarantee.","has_mixed_bases is true when branches come from different analyses. Compare different snapshots carefully and re-scan if the live account has changed."],`{
  "base_analysis_id": "analysis_123",
  "branches": [{ "branch_id": "branch_456", "name": "restrict-public-access", "score_after": 78, "score_delta": 6, "added_nodes": 0, "removed_nodes": 0, "newly_internet_reachable": 0, "no_longer_internet_reachable": 1, "added_findings": 0, "removed_findings": 1, "has_privilege_escalation": false }],
  "ranking": ["branch_456"], "has_mixed_bases": false, "base_analysis_ids": ["analysis_123"]
}`],
  "tool-check-compliance":["emfirge_check_compliance","Evaluate CIS AWS Foundations 1.5 or SOC 2 controls against a scan as one focused analysis lens.","analysis_id: string · required; framework: cis-aws-1.5 | soc2 · optional",`{
  "analysis_id": "7f3c9a2e-4b1d-4c8a-9f2e-1a2b3c4d5e6f",
  "framework": "cis-aws-1.5"
}`, ["Omit framework to receive both CIS AWS Foundations 1.5 and SOC 2. The top level contains analysis_id, frameworks, and fired_rule_ids.","Each framework reports id, name, version, totalControls, passedControls, failedControls, naControls, sections, and controls. Each control includes id, title, section, status, mappedRuleId, and description. Every failed control links to the rule that caused it through mappedRuleId; fired_rule_ids lists every rule that triggered.","CIS AWS Foundations 1.5 has 29 controls and SOC 2 has 12. Each finding carries MITRE ATT&CK mapping. Results are read-only and do not constitute certification."],`{
  "analysis_id": "7f3c9a2e-4b1d-4c8a-9f2e-1a2b3c4d5e6f",
  "frameworks": [{
    "id": "cis-aws-1.5", "name": "CIS AWS Foundations", "version": "1.5", "totalControls": 29,
    "passedControls": 5, "failedControls": 24, "naControls": 0,
    "sections": [{ "id": "1", "title": "Identity and Access Management" }],
    "controls": [{ "id": "1.2", "title": "Ensure MFA enabled for all IAM users", "section": "1", "status": "fail", "mappedRuleId": "EMFIRGE-IAM-003", "description": "Users without MFA detected" }]
  }],
  "fired_rule_ids": ["EMFIRGE-EC2-002", "EMFIRGE-IAM-003", "…"]
}`],
  "tool-discard-branch":["emfirge_discard_branch","Discard an isolated branch when it is no longer needed; this does not change AWS.","branch_id: string · required",`{ "branch_id": "branch_456" }`, ["Discard is a soft state change. A discarded branch remains identifiable but is no longer open for applying changes.","Discarding a branch does not deploy, delete, or roll back any AWS resource."],`{ "branch_id": "branch_456", "status": "discarded" }`],
  "tool-simulate-breach":["emfirge_simulate_breach","Run a natural-language what-if against the modeled cloud graph to trace entry → pivot → impact, blast radius, and follow-up moves.","analysis_id: string · required; query: string (3–500 characters) · required",`{
  "query": "what gets exposed if NAME_132 opens port 80",
  "analysis_id": "7f3c9a2e-4b1d-4c8a-9f2e-1a2b3c4d5e6f"
}`, ["query accepts scenarios such as ‘what gets exposed if NAME_132 opens port 80’ or ‘show the worst attack path’; tokens like NAME_132 are expanded locally.","The response includes verdict, severity, summary, stages, blast_radius, follow_up, and category. Each stage has order, caption, node_ids, and color (red or amber); entry→pivot→impact is conveyed by order and color, not a phase field.","blast_radius is an object with total and a by_type tally. follow_up is one suggested next question. In MCP mode the backend skips its prose summary (the host LLM writes it), so the result is deterministic and returns in a few seconds. It is read-only and does not execute an exploit or change AWS."],`{
  "verdict": "Full data exfiltration path exists. 1 database, 1 S3 bucket, 1 secret reachable from the internet in 7 hops.",
  "severity": "critical", "summary": "An attacker can reach your data stores in 7 hops…",
  "stages": [
    { "order": 1, "caption": "Attacker lands on EC2: NAME_138 via open security group", "node_ids": ["NAME_138", "NAME_139", "NAME_140"], "color": "red" },
    { "order": 2, "caption": "EC2: NAME_138 assumes IAM Role: AppServerRole, credential theft possible", "node_ids": ["iam-role-AppServerRole"], "color": "red" },
    { "order": 3, "caption": "IAM role accesses RDS: acme-prod-customers, data exfiltration risk", "node_ids": ["acme-prod-customers"], "color": "amber" }
  ],
  "blast_radius": { "total": 23, "by_type": { "EC2": 7, "SG": 5, "RDS": 1, "S3": 1 } },
  "follow_up": "What specific data can be exfiltrated from the exposed storage?", "category": "attack_surface"
}`]
};
for (const [slug, [title, description, params, ask, details, response]] of Object.entries(toolInfo)) legacyDocs.push(extra(slug,title,"MCP tools",description,[section("parameters","Parameters",[params],{code:ask,language:"MCP ask / arguments"}),section("returns","Returns",["The response is JSON shaped for the operation. The fields and semantics are described below."],{code:response,language:"JSON response"}),section("details","Validation, behavior, and limits",details)]));
// Rebuilt standalone pages: preserve the original route content in the structured docs model.
const rebuilt = (slug: string) => legacyDocs.find(d => d.slug === slug)!;
rebuilt("how-it-works").sections.push(
  section("graph-detail", "The graph", ["A scan reads the cloud through a read-only role and builds a connected infrastructure graph. The graph is the saved base for subsequent analysis; it is not a live write target and becomes stale as the account changes."]),
  section("workflow-detail", "Complete workflow", ["The flow is: read-only scan → fork graph → apply modeled branch change → diff the branch → re-run analysis lenses → advisory verdict.", "Use `emfirge_create_branch` to fork a completed analysis, add an `emfirge_apply_change` operation to the isolated model, then inspect `emfirge_branch_diff` and `emfirge_branch_verdict`. The verdict combines modeled native findings with available scanner lenses and reports coverage explicitly."], {code:'emfirge_create_branch({ base_analysis_id: "<analysis_id>", name: "restrict-public-access" })\nemfirge_apply_change({ branch_id: "<branch_id>", op: "modify", resource_type: "rds_instance", resource_id: "<database_id>", fields: { publicly_accessible: false } })\nemfirge_branch_diff({ branch_id: "<branch_id>" })\nemfirge_branch_verdict({ branch_id: "<branch_id>" })', language:"MCP tool calls"}),
  section("six-lenses", "The six branch-verdict lenses", ["A branch verdict compares the modeled base and proposed branch across six lenses. Each lens answers a concrete AWS question, exposes its exact verdict fields, and states what the model cannot establish."], {table:{headers:["AWS question","CombinedVerdict mapping","Honest bound","Worked example"],rows:[
    ["Security — Which native findings are new or removed?","CombinedVerdict.native_added / CombinedVerdict.native_removed","58 native rule IDs across 17 native service families cover defined families, not every possible issue.","Opening SSH to 0.0.0.0/0 adds an internet-reachable EC2 finding."],
    ["Reachability — What becomes or stops being reachable from the internet?","CombinedVerdict.newly_internet_reachable / CombinedVerdict.no_longer_internet_reachable","Modeled graph reachability, not a live connectivity probe.","Attaching a public subnet path makes a modeled service newly internet-reachable."],
    ["Blast radius — What paths are reachable from a compromised node?","No standalone blast-radius or attack-path CombinedVerdict field; related finding and attack-path payloads expose it, while the verdict summarizes resulting finding deltas.","Only modeled graph edges, known resources, and known paths.","A compromised modeled role reaching a data store appears in its attack-path payload."],
    ["IAM privilege escalation — Does the change introduce an IAM escalation path?","CombinedVerdict.introduces_privilege_escalation. Policy/action metadata from Policy Sentry informs upstream analysis; its annotations are not CombinedVerdict fields.","IAM policy/action coverage and modeled principals, not proof of exploitability.","Adding a modeled pass-role path marks privilege escalation as introduced."],
    ["Cost — What is the provisioned monthly cost delta?","CombinedVerdict.cost_delta_monthly_usd / CombinedVerdict.cost_unknown_notes","Usage-based costs remain unknown and labeled; Emfirge never fabricates them.","Adding a provisioned resource produces a monthly delta while usage-based charges remain unknown."],
    ["Limits / capacity — Which limits does the change approach or breach?","CombinedVerdict.limits_introduced / CombinedVerdict.limits_resolved","Deterministic checks, not forecasting or a live quota guarantee.","Adding resources beyond a modeled service limit adds a capacity finding."]
  ]}}),
  section("borrowed-scanners", "Borrowed scanners and coverage", ["Checkov, Trivy, and cloudsplaining run at arm's length against the branch when available; they do not become native rules. Their findings fold into `scanner_added` and `scanner_removed` alongside the same combined verdict.", "Missing executable or package, timeout, invalid or empty output, disabled scanner, or another unavailable state degrades honestly: `scanner_status` reports each state and `coverage_warnings` says the result is NOT full coverage. Do not assume all scanners always run." ]),
  section("combined-detail", "Combined verdict", ["`block`, `warn`, or `pass` combines native and scanner deltas, reachability, cost, privilege escalation, limits, and the human-readable `summary` into one advisory result. It proves the change against a model, not the live cloud: it computes a security delta and never guarantees safety.", "`coverage_warnings` is non-empty when lenses are missing or disabled. A degraded result must not be described as complete coverage or a guarantee of safety. A pass means no modeled concern was found by available analysis, not that deployment is risk-free."])
);
rebuilt("graph").sections.push(
  section("typed-graph", "Typed nodes and edges", ["Every resource a scan finds becomes a node. Every real relationship becomes a directed edge. The public internet is a first-class node, so internet reachability is a literal path. The engine models roughly 20 service types."], {bullets:["internet", "vpc", "subnet", "security_group", "ec2_instance", "load_balancer", "iam_role", "rds_instance", "s3_bucket", "lambda_function", "ecs_tasks", "api_gateway", "elasticache", "dynamodb_table", "cloudfront", "secrets_manager", "kms_key", "sqs_queue", "ebs_volume", "elastic_ip"]}),
  section("edge-types", "Relationships and effort weights", ["Edges encode `REACHES` (internet to security group), `uses_iam_role` (instance assuming a role), `can_access` (role reaching a data store), `REFERENCES_SECRET`, subnet/VPC containment, and more. Findings hang off the nodes and edges that produced them.", "Every edge type carries exploit difficulty from 0 to 3. A five-hop route of trivial steps can outrank a two-hop route needing a shell and stolen credentials: ranking is by effort, not distance."], {table:{headers:["Weight","Meaning","Example edges"],rows:[["0","Structural, not an exploit step","instance ↔ security group, subnet / VPC containment, Lambda → VPC"],["1","Trivial, automated scanners","Internet → security group, Internet → instance, CloudFront → S3 origin"],["2","Needs a step (bypass or valid call)","load balancer → instance, role → data store, Lambda → secret"],["3","Needs a shell plus credential theft","instance → IAM role, ECS task → IAM role"]]}}),
  section("derived-queries", "Derived queries", ["Attack paths are weighted shortest-path searches outward from the internet, returning routes to data ranked by effort; this is what `emfirge_attack_paths` returns.", "Blast radius is a directional outbound-only search: if one resource is compromised, everything it could reach next. Inbound edges are ignored, so the result is downstream risk, not what protects the resource.", "Chokepoints use betweenness centrality to find nodes on paths between others. Toxic combinations are 9 curated multi-signal patterns. Orphaned resources are disconnected nodes such as unattached EBS volumes or idle elastic IPs, usually cleanup/cost signals."]),
  section("coverage-counts", "Service coverage, rules, and scoring", ["The engine runs 58 deterministic rules across 17 service families: EC2 and security groups, S3, RDS, IAM, Lambda, KMS, VPC, CloudTrail, Config, CloudWatch, GuardDuty, Secrets Manager, SNS, WAF, ECS, cost, and orphaned resources.", "Findings roll into a 0–100 scan posture score (higher is safer) across security, availability, cost, and disaster recovery. Severity is context-aware: SSH open behind an ALB is not scored like SSH open to the internet. No LLM runs in scoring. This posture score is distinct from the branch verdict, which evaluates six change lenses."]),
  section("graph-limits", "Graph limits", ["The graph is a scan snapshot, not live AWS; re-scan after infrastructure changes. Coverage is roughly 20 service types, so anything outside it cannot appear in paths, blast radius, or chokepoints. Weights 0–3 are hand-assigned heuristics, not real-world exploitability measurements. Paths and blast radius are capped at 5 hops; blast radius is a downstream reachability count, not proof every step can be chained. The 9 toxic patterns are not exhaustive, and normalized scores are only approximately comparable across very different accounts."])
);
rebuilt("security").sections.push(
  section("role-detail", "Exact role permissions and trust", ["Setup creates a role with AWS's managed `SecurityAudit` policy plus a small set of extra read permissions. It has no write permissions of any kind. The role trust uses ExternalId `aws-risk-agent` to prevent confused-deputy attacks and is scoped so only Emfirge's AWS account (`000000000000`) can assume it."], {bullets:["Read-only, zero write permissions.","STS credentials are temporary, expire after one hour, and are never stored.","Delete the CloudFormation stack for instant revoke."]}),
  section("setup-detail", "Setup steps", ["Ask your assistant ‘help me set up Emfirge’ for a pre-filled deploy link. Open it in AWS, tick the IAM-resources checkbox and create the stack (about 30 seconds), copy `RoleArn` from Outputs (it starts `arn:aws:iam::`), and give the ARN back to your assistant so the scan runs."]),
  section("retention-detail", "Retention and errors", ["Scanning, rules, graph analysis, and verify-fix are deterministic pure computation; prose summaries are the only model-generated part and never run inside the MCP path. The backend stores scan data for 90 days then auto-deletes; `npx @emfirge/mcp purge --role-arn <ARN>` wipes it immediately.", "403 means access denied: check trust policy and ExternalId. 404 means the `analysis_id` was not found: run `emfirge_scan` first. 429 means the five-scans-per-account-per-day limit was reached; it resets at midnight UTC."], {table:{headers:["HTTP code","Meaning"],rows:[["403","Access denied; check trust policy and ExternalId `aws-risk-agent`."],["404","`analysis_id` not found; run `emfirge_scan` first."],["429","Daily limit of 5 scans per account; resets at midnight UTC."]]}})
);
rebuilt("privacy").sections.push(
  section("mode-definitions", "The three modes", ["`strict` (default) tokenizes recognized AWS IDs, ARNs, account IDs, resource names, and IP addresses; it is the strongest default boundary for sensitive transcripts.", "`balanced` tokenizes common identifiers such as ARNs, compute/network/IAM IDs, IPs, and account IDs while retaining selected infrastructure context; it balances context and minimization.", "`off` leaves identifiers un-tokenized so they may reach the LLM as returned; use only when raw identifiers are acceptable."]),
  section("client-config", "Changing modes and client environment", ["Use `npx @emfirge/mcp privacy` to show the current mode or `npx @emfirge/mcp privacy strict` to set strict, balanced, or off. When configuring a client directly, set `EMFIRGE_PRIVACY` in the MCP client configuration."], {code:"npx @emfirge/mcp privacy          # show current mode\nnpx @emfirge/mcp privacy strict   # set strict, balanced, or off\n\"env\": { \"EMFIRGE_PRIVACY\": \"strict\" }", language:"Terminal / client config"}),
  section("boundary-detail", "Backend and report URLs", ["The backend receives the data required for the requested scan and analysis. Credentials embedded in presigned report URLs are scrubbed before URLs are returned or displayed. Do not share raw credentials or unreviewed transcripts. Derived graph labels or descriptive values may not be recognized identifiers, so tokenization is not a completeness guarantee; review outputs against organizational policy, especially in strict mode."])
);
rebuilt("cli").sections.push(
  section("complete-commands", "Complete command reference", ["With no subcommand, the package runs as an MCP stdio server for the AI client; with a subcommand it manages installation. `install` detects Claude Desktop, Cursor, Kiro, Cline, Continue, and Codex CLI and adds the server to each config it finds. It prompts for privacy unless `--privacy` is passed; accepted values are `strict | balanced | off`, defaulting to `strict` and supporting scripts/CI. `uninstall` removes the server from all clients."], {code:"npx @emfirge/mcp install                       # wire into all detected clients\nnpx @emfirge/mcp install --privacy=balanced    # non-interactive: skip prompt\nnpx @emfirge/mcp uninstall                      # remove from all clients\nnpx @emfirge/mcp status                         # wired clients, backend URL, privacy mode\nnpx @emfirge/mcp privacy                       # show current privacy mode\nnpx @emfirge/mcp privacy strict|balanced|off   # set privacy mode everywhere\nnpx @emfirge/mcp tokens                         # list local token mappings\nnpx @emfirge/mcp purge --role-arn <ARN>         # delete local + server scan data\nnpx @emfirge/mcp --version                      # print version\nnpx @emfirge/mcp --help                         # print usage", language:"Terminal"}),
  section("behavior", "Status, privacy, tokens, and purge", ["`status` prints wired clients, backend URL, and active privacy mode. `privacy` with no argument prints the current mode; with strict, balanced, or off it updates every wired client. `tokens` lists local token → real-ID mappings at `~/.emfirge/tokens.json`; this file never leaves your machine. `purge --role-arn <ARN>` deletes the local token map and server-side records for that role permanently, with no undo."], {code:"npx @emfirge/mcp purge --role-arn <ARN>", language:"Terminal", note:"Irreversible"})
);
rebuilt("self-host").sections.push(
  section("dashboard-detail", "Dashboard URL derivation", ["The hosted default is `https://emfirge.cloud/api`. Set `EMFIRGE_BASE_URL` in each client’s MCP server config; the thin MCP calls backend endpoints and tokenizes responses locally, so a self-hosted backend behaves identically. The web dashboard URL derives from the API base by stripping `/api`, so verify-fix ‘open a PR’ links point at your own domain automatically."], {code:`{\n  "mcpServers": {\n    "emfirge": {\n      "command": "npx",\n      "args": ["-y", "@emfirge/mcp"],\n      "env": {\n        "EMFIRGE_BASE_URL": "https://emfirge.internal.acme.com/api",\n        "EMFIRGE_PRIVACY": "strict"\n      }\n    }\n  }\n}`, language:"mcp.json"}),
  section("all-env", "Complete environment configuration", ["Configure these variables in each MCP client server environment."], {table:{headers:["Variable","Type","Purpose and default"],rows:[["EMFIRGE_BASE_URL","url","Backend URL; default https://emfirge.cloud/api. Override to self-host."],["EMFIRGE_PRIVACY","strict | balanced | off","Tokenization mode; default strict."],["EMFIRGE_TRUSTED_ACCOUNT_ID","string","AWS account ID the generated role trusts; default 000000000000. Set your own account when self-hosting so setup_help trusts your scanner."],["EMFIRGE_EXTERNAL_ID","string","ExternalId required in trust policy; default aws-risk-agent."],["EMFIRGE_TEMPLATE_URL","url","CloudFormation URL used by setup_help; override to ship your own role template."]]}}),
  section("license-detail", "Open-source license", ["The MCP and a public mirror of the backend are open source under BUSL 1.1: free for non-production and small production use, converting to Apache 2.0 in 2030."])
);
rebuilt("faq").sections.push(
  section("all-questions", "FAQ: all operational questions", ["Do I need to be a security expert? No. Ask normal questions such as ‘What should I fix first?’, ‘How could someone reach my database?’, or ‘Would this change help?’; Emfirge analyzes and your assistant explains in everyday language.", "What do I need? An AWS account, target region, and read-only connection; the setup can be removed whenever you want. MCP is simply the assistant connection, and the installer wires supported desktop assistants. A browser dashboard is also available.", "Can I try it without connecting my account? Yes: the demo uses made-up infrastructure with the real analysis engine and shares nothing from your AWS account.", "Will it change or delete anything? No. It has read-only access and tests fixes on a temporary copy of the cloud map; you decide what happens next.", "Is it safe to connect? The role belongs to you, access is temporary, it cannot make AWS changes, and deleting the setup stack revokes it.", "Who can see AWS names and IDs? The backend needs real details for analysis; default privacy replaces recognized names and IDs before results reach the assistant, though some derived labels may remain. Review sensitive results before sharing.", "How long and how often? Scans usually take 30–60 seconds, larger accounts longer; the daily limit is five per AWS account. Findings, attack routes, possible fixes, and compliance checks after a scan use no additional scan.", "What after a finding? Inspect the top-ranked item and affected routes, test the suggested fix, then have your team review and apply it.", "Does it cover everything? Not yet: coverage is common AWS services and modeled relationships, not every possible issue.", "Can I self-host? Yes; follow the Self-hosting guide, with an engineer’s help if needed."], {note:"Open the Quickstart and try the demo before connecting your own account."})
);
documents.push(...legacyDocs);
