"use client";
import { useEffect,useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowUpLeft, FileText, Search, X } from "lucide-react";
import { searchEntries } from "./nav";
export function DocsSearch({open,onClose}:{open:boolean;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const input=useRef<HTMLInputElement>(null);const router=useRouter();
 const [query,setQuery]=useState("");const [selected,setSelected]=useState(0);
 const terms=query.toLowerCase().trim().split(/\s+/).filter(Boolean);
 const results=(terms.length?searchEntries.filter(entry=>terms.every(term=>`${entry.search} ${entry.title}`.toLowerCase().includes(term))).sort((a,b)=>Number(b.title.toLowerCase().includes(query.toLowerCase()))-Number(a.title.toLowerCase().includes(query.toLowerCase()))):searchEntries.filter(entry=>!entry.href.includes("#"))).slice(0,9);
 useEffect(()=>{if(open){setQuery("");setSelected(0);dialog.current?.showModal();input.current?.focus();}else dialog.current?.close();},[open]);
 function go(href:string){onClose();router.push(href);}
 return <dialog ref={dialog} className="docs-search-dialog" onCancel={onClose} onClick={event=>{if(event.target===event.currentTarget)onClose();}} aria-labelledby="search-title"><div className="search-box"><h2 id="search-title" className="sr-only">Search Emfirge documentation</h2><div className="search-input-row"><Search size={20}/><input ref={input} aria-label="Search documentation" role="combobox" aria-expanded="true" aria-controls="search-results" aria-activedescendant={results[selected]?`search-result-${selected}`:undefined} autoComplete="off" value={query} placeholder="Search documentation…" onChange={e=>{setQuery(e.target.value);setSelected(0);}} onKeyDown={e=>{if(e.key==="ArrowDown"){e.preventDefault();setSelected(s=>Math.min(s+1,results.length-1));}if(e.key==="ArrowUp"){e.preventDefault();setSelected(s=>Math.max(s-1,0));}if(e.key==="Enter"&&results[selected]){e.preventDefault();go(results[selected].href);}}}/><button className="icon-button" onClick={onClose} aria-label="Close search"><X size={18}/></button></div><p className="search-caption">{query?`${results.length} matching ${results.length===1?"result":"results"}`:"Explore the documentation"}</p><div role="listbox" id="search-results" aria-label="Search results" className="search-results">{results.map((entry,index)=><button role="option" aria-selected={selected===index} id={`search-result-${index}`} key={entry.href} className={index===selected?"selected":""} onMouseMove={()=>setSelected(index)} onClick={()=>go(entry.href)}><FileText size={17}/><span><small>{entry.group}</small><strong>{entry.title}</strong><span className="search-description">{entry.description.replace(/`/g,"")}</span></span><ArrowUpLeft size={15}/></button>)}{!results.length&&<div className="search-empty"><Search size={24}/><strong>No results for “{query}”</strong><p>Try “branch”, “AWS role”, “privacy”, or a tool name.</p></div>}</div><div className="search-footer"><span><kbd>↑</kbd><kbd>↓</kbd> to navigate</span><span><kbd>↵</kbd> to open</span><span><kbd>esc</kbd> to close</span></div></div></dialog>;
}
