"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { ArrowUpRight, Menu, Moon, Search, Sun, X } from "lucide-react";
import { BrandMark } from "@/components/brand-mark";
import { SOURCE_URL } from "./content";
export function DocsTopBar({onSearch,onMenu,mobileOpen,theme,onTheme}:{onSearch:()=>void;onMenu:()=>void;mobileOpen:boolean;theme:"dark"|"light";onTheme:()=>void}) {
 const pathname=usePathname();
 const tabs=[{label:"Overview",href:"/docs",active:pathname==="/docs"||pathname==="/docs/quickstart"||pathname==="/docs/concepts"},{label:"Branches",href:"/docs/branches",active:["/docs/branches","/docs/changes","/docs/diffs"].includes(pathname)},{label:"Lenses",href:"/docs/lenses",active:["/docs/lenses","/docs/safety"].includes(pathname)},{label:"MCP reference",href:"/docs/mcp",active:["/docs/mcp","/docs/configuration"].includes(pathname)},{label:"Resources",href:"/docs/faq",active:["/docs/faq","/docs/glossary","/docs/troubleshooting"].includes(pathname)}];
 return <header className="docs-header"><div className="header-main"><Link className="docs-brand" href="/" aria-label="Emfirge documentation home"><BrandMark className="size-7"/><span>Emfirge<span className="brand-label"> Developers</span></span></Link><nav className="header-links" aria-label="Main navigation"><Link href="/docs" className={pathname!=="/connect"?"selected":""}>Documentation</Link><a href={SOURCE_URL} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={13}/></a></nav><div className="header-actions"><Link className="button-primary header-connect" href="/connect">Connect agent <ArrowUpRight size={14}/></Link><button className="icon-button" onClick={onTheme} aria-label={`Switch to ${theme==="dark"?"light":"dark"} theme`}>{theme==="dark"?<Moon size={18}/>:<Sun size={18}/>}</button><button className="icon-button header-search" onClick={onSearch} aria-label="Search documentation"><Search size={18}/></button><button className="icon-button mobile-menu-button" onClick={onMenu} aria-label={mobileOpen?"Close navigation":"Open navigation"} aria-expanded={mobileOpen} aria-controls="mobile-docs-nav">{mobileOpen?<X size={20}/>:<Menu size={20}/>}</button></div></div><nav className="header-tabs" aria-label="Documentation sections">{tabs.map(tab=><Link href={tab.href} key={tab.href} className={tab.active?"active":""}>{tab.label}</Link>)}</nav></header>;
}
