import { DocHeader, Lead, H2, P, Strong, Code, Callout, PrevNext } from "@/components/docs/ui";
import { CodeBlock } from "@/components/docs/code-block";
import { prevNext } from "@/lib/nav";
export const metadata = { title: "Privacy modes · Emfirge Docs", description: "strict, balanced, and off privacy modes and public data boundaries." };
function ModeRow({ mode, tokenized, best, def }: { mode: string; tokenized: string; best: string; def?: boolean }) { return <div className="grid grid-cols-[6rem_1fr] gap-4 border-b border-border-soft py-4 sm:grid-cols-[8rem_1.3fr_1fr]"><div><code className="font-mono text-[13px] font-medium text-foreground">{mode}</code>{def && <span className="ml-2 text-[10.5px] font-medium uppercase tracking-wide text-safe">Default</span>}</div><div className="text-[13.5px] leading-relaxed text-muted-foreground">{tokenized}</div><div className="text-[13px] leading-relaxed text-muted-foreground">{best}</div></div>; }
export default function Page() { const { prev, next } = prevNext("/docs/privacy"); return <><DocHeader eyebrow="Privacy & Trust" title="Privacy modes"><Lead>Privacy mode controls what the local MCP tokenizes before tool results reach your LLM. The mapping remains on your machine and is not sent to Emfirge or the model.</Lead></DocHeader><H2>How tokenization works</H2><P>The MCP replaces recognized AWS identifiers in responses with stable local tokens. When a later tool call uses one of those tokens, it expands the token locally, calls the backend, and tokenizes the response again. The backend still receives the identifiers needed to read AWS.</P><CodeBlock tabs={[{ label: "example", code: `LLM sees:       "SG_001 reaches S3_001"
local mapping:  SG_001 = <local security-group ID>
                S3_001 = <local bucket ID>` }]} /><H2>The three modes</H2><div className="mt-4"><ModeRow mode="strict" def tokenized="Recognized AWS IDs, ARNs, account IDs, resource names, and IP addresses are tokenized." best="Strongest default boundary for sensitive transcripts." /><ModeRow mode="balanced" tokenized="Common identifiers such as ARNs, compute/network/IAM IDs, IPs, and account IDs are tokenized; selected infrastructure context may remain raw." best="A practical balance of context and minimization." /><ModeRow mode="off" tokenized="Identifiers are not tokenized by the MCP and may reach the LLM as returned." best="Only when raw identifiers are acceptable." /></div><H2>Changing modes</H2><CodeBlock tabs={[{ label: "terminal", code: `npx @emfirge/mcp privacy          # show current mode
npx @emfirge/mcp privacy strict   # set strict, balanced, or off` }]} /><P>Set <Code>EMFIRGE_PRIVACY</Code> in the MCP client configuration when configuring a client directly.</P><H2>Backend and report URLs</H2><Callout type="note" title="Public-safe boundary">The backend receives the data required to perform the requested scan and analysis. Credentials embedded in presigned report URLs are scrubbed before those URLs are returned or displayed. Do not share raw credentials or unreviewed transcripts.</Callout><Callout type="warning" title="Tokenization is not a completeness guarantee">Some derived graph labels or descriptive values may not be recognized identifiers. Review outputs against your organization&apos;s policy, especially in strict mode.</Callout><PrevNext prev={prev} next={next} /></>; }
